{% set name = "xlandsat" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/xlandsat-{{ version }}.tar.gz
  sha256: 6d8b8ad9876f72227e2bb06f556f5a815446c9a7b8f5aedbbd6b38aa4fd04a6f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm
    - tomli
  run:
    - python >={{ python_min }}
    - numpy >=1.19
    - scipy >=1.5
    - xarray >=0.16
    - scikit-image >=0.18
    - pooch >=1.3.0

test:
  imports:
    - xlandsat
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/compgeolab/xlandsat
  summary: Analyze Landsat remote sensing images using xarray
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - leouieda
