{% set name = "xlandsat" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xlandsat-{{ version }}.tar.gz
  sha256: e51eaae22fb43498516ff47337114090e41b78723177cdc1622e1523d2aa54bb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
    - setuptools_scm
    - tomli
  run:
    - python >=3.7
    - numpy >=1.19
    - xarray >=0.16
    - scikit-image >=0.18
    - pooch >=1.3.0

test:
  imports:
    - xlandsat
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/compgeolab/xlandsat
  summary: Load Landsat remote sensing images into xarray
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - leouieda
