{% set name = "xlandsat" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xlandsat-{{ version }}.tar.gz
  sha256: cbadcf04241dcab19ea3ba5d88fcf83e4dc174e4ed8a56886ae717c77470a8aa

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
    - setuptools_scm
    - tomli
  run:
    - python >=3.7
    - numpy >=1.19
    - xarray >=0.16
    - scikit-image >=0.18

test:
  imports:
    - xlandsat
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/compgeolab/xlandsat
  summary: Load Landsat remote sensing images into xarray
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - leouieda
